name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # 1. Checkout main
      - name: Checkout main
        uses: actions/checkout

      # 2. Checkout pages branch into ./pages
      - name: Checkout pages branch
        uses: actions/checkout
        with:
          repository: ${{ github.repository }}
          ref: pages
          path: pages

      # 3. Copy everything except dot-files into pages/contents
      - name: Copy files to pages/contents
        run: |
          cd pages
          mkdir -p contents
          shopt -s extglob
          cp -R ../!(.*) contents/

      # 4. Commit & push to pages
      - name: Commit pages updates
        run: |
          cd pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add contents
          if ! git diff --cached --exit-code; then
            git commit -m "chore: sync content from main on ${{ github.sha }}"
            git push origin pages
          else
            echo "No content changes"
          fi

      # 5. Install & build Quartz
      - name: Setup Node
        uses: actions/setup-node
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Build Quartz
        run: npx quartz build

      # 6. Upload the built site for Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages
