name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # 1. Checkout main
      - name: Checkout main
        uses: actions/checkout@v4

      # 2. Checkout pages branch into ./pages
      - name: Checkout pages branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: pages
          path: pages

      # 3. Copy non-dot files into pages/contents
      - name: Sync content to pages/contents
        run: |
          cd pages
          mkdir -p content
          shopt -s extglob
          # copy everything from the parent except:
          #  • dot-files/dirs (.*)
          #  • the pages folder itself (“pages”)
          #  • the contents folder we just made (“contents”)
          cp -R ../!(.*|pages|content) content/
      # 4. Commit & push back to pages
      - name: Commit pages updates
        run: |
          cd pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add contents
          if ! git diff --cached --exit-code; then
            git commit -m "chore: sync content from main @ ${{ github.sha }}"
            git push origin pages
          else
            echo "No content changes to commit"
          fi

      # 5. Install & build Quartz
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          cd pages
          npm ci

      - name: Build Quartz
        run: | 
          cd pages
          npx quartz build

      # 6. Upload build for Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

